public class Exception_handling_19 {
    public static void main(String[] args) {
        try {
            int a = 10 / 0;
        } catch (ArithmeticException e) {
            System.out.println("you divided by zero");
        }
    }
}